stages:
- build

build:
  image: mwienk/docker-bolt-builder
  stage: build
  script:
     - composer install --no-dev
     - rm -rf .git*
     - mkdir ../beslistcart
     - mv * ../beslistcart
     - mv ../beslistcart .
  artifacts:
    paths:
      - .